### ISSUE TITLE
Add candidate responses

### ISSUE THREAD

**Issue by changecase** [bikewalkvote/bikewalkvote.github.io#3]
The following candidates need their responses added to the site:
- [x] Bob Stacey
- [x] Craig Dirksen
- [x] Gerritt Rosenthal
- [x] Jessica Vega Pederson
- [x] Sarah Iannarone
- [x] Jules Bailey
- [x] Ted Wheeler
- [x] Mel Rader
- [x] Sam Chase
- [x] Steve Novick
- [x] Tawna Sanchez

**Comment by alankessler** [comment]
I think this is complete

**Comment by changecase** [comment]
Awesome!
