### ISSUE TITLE
We need Access to mailchimp -- I think the account is: techieshark

### ISSUE THREAD

**Issue by alankessler** [bikewalkvote/bikewalkvote.github.io#9]
[redacted]

**Comment by changecase** [comment]
[redacted]

**Comment by techieshark** [comment]
I have access. @changecase I've emailed you about this.

**Comment by techieshark** [comment]
Also, not that you would, but just a reminder - this gh repo is public, so don't share anything private here.

**Comment by changecase** [comment]
I don't seem to have anything recent from @techieshark, but I found a message from several years ago that I've sent @alankessler's way.

**Comment by alankessler** [comment]
It worked. Thanks!
